#!/bin/bash

curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1], "block": [1, 1, 1], "path": [{"movie-service": 1}, {"image-service": 1}], "visited":[]}'
curl -X POST $1 --data '{"requestID": 0, "process":[1, 1, 1 ], "block": [1, 1, 1], "path": [{"rating-service":1}], "visited":[]}'



eval $(docker-machine env swarm-m)
docker-machine scp -r swarm-1:/var/log/micro .
docker-machine scp -r swarm-2:/var/log/micro .
